name: Waka Watch
description: WakaTime on your Apple Watch
full_description:
  "Waka Watch allows you to view your WakaTime stats right on your Apple Watch.<br/>Features:
  <ul><li>- View your daily coding activity on your Apple Watch face.
  <li>- Get notifications on your Apple Watch when you&apos;ve completed a WakaTime goal.
  <li>-See your coding summary over 5 days and your position on the public leaderboard.
  </li></ul>"
iOS: https://apps.apple.com/us/app/waka-watch/id1607453366
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
